"""
main_option_c.py
================
Option C pipeline: honest validation using Gabriel's full dielectric
model (4-Cole-Cole) with a band-limited (beta sub-band) fit.

BEFORE RUNNING -- MANDATORY STEP
====================================
The full delta_eps_n / tau_n / alpha_n parameters for each tissue in
`src/gabriel_4cc_model.py` (MUSCLE_4CC_PARTIAL) are marked as
UNVERIFIED. Before using this pipeline for the final paper:

  1. Go to: https://www.fcc.gov/general/body-tissue-dielectric-parameters
  2. Select the "Muscle" tissue
  3. For each frequency in your grid (e.g. 100 Hz, 215 Hz, 464 Hz, ...,
     1 MHz -- 30 log-spaced points), note eps' (Permittivity) and
     sigma (Conductivity, S/m)
  4. Fill in `fcc_lookup_data.csv` (generated by `--generate-template`)
     with the real looked-up values
  5. Run the pipeline with `--csv-fcc fcc_lookup_data.csv`

This removes any risk of parameter transcription error and makes the
validation 100% traceable to the official source.

Usage:
    # Generate a CSV template to fill in using the official calculator
    python main_option_c.py --generate-template

    # Run with real data looked up on the FCC site
    python main_option_c.py --csv-fcc fcc_lookup_data.csv

    # Demo mode (uses UNVERIFIED parameters -- code testing only)
    python main_option_c.py --demo --fast
"""

import argparse
import os
import csv
import warnings
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore", category=RuntimeWarning)

from src.gabriel_4cc_model import (
    MUSCLE_4CC_PARTIAL, impedance_from_4cc, impedance_from_4cc_calibrated,
    impedance_from_eps_sigma, select_beta_band, fit_single_cole_cole_subband
)
from src.itis_database_loader import (
    generate_itis_csv_template, load_itis_csv, validate_physical_parameters
)
from src.data_generation import frequency_grid
from src.cole_model import cole_cole_impedance

plt.rcParams.update({"figure.dpi": 130, "axes.spines.top": False,
                      "axes.spines.right": False, "font.size": 11})


# ===========================================================================
# CSV template for the manual official-calculator lookup
# ===========================================================================

def generate_fcc_csv_template(filepath="fcc_lookup_data.csv",
                               n_freq=30, f_min=100.0, f_max=1e6):
    """Generate a CSV template with the frequency grid to look up on the official FCC/IFAC-CNR calculator."""
    f = frequency_grid(f_min, f_max, n_freq)
    with open(filepath, "w", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["freq_hz", "eps_prime", "sigma_S_per_m", "source"])
        for fi in f:
            writer.writerow([f"{fi:.4f}", "", "", ""])

    print(f"\nTemplate saved to: {filepath}")
    print(f"\n{'='*70}")
    print("  NEXT STEP (manual, ~5 minutes):")
    print(f"{'='*70}")
    print("  1. Go to: https://www.fcc.gov/general/body-tissue-dielectric-parameters")
    print("  2. Select the tissue (e.g. Muscle)")
    print(f"  3. For each of the {n_freq} frequencies in the CSV, look up")
    print("     eps' (permittivity) and sigma (conductivity, S/m)")
    print("  4. Fill in the 'eps_prime' and 'sigma_S_per_m' columns")
    print(f"  5. Run: python main_option_c.py --csv-fcc {filepath}")
    print(f"{'='*70}\n")
    return filepath


def load_fcc_csv(filepath):
    """Load a CSV filled with values looked up on the FCC/IFAC-CNR calculator."""
    freqs, eps_vals, sigma_vals = [], [], []
    with open(filepath, "r") as fh:
        for row in csv.DictReader(fh):
            try:
                freqs.append(float(row["freq_hz"]))
                eps_vals.append(float(row["eps_prime"]))
                sigma_vals.append(float(row["sigma_S_per_m"]))
            except (ValueError, KeyError):
                continue

    if len(freqs) < 5:
        raise ValueError(
            f"CSV '{filepath}' has only {len(freqs)} filled rows. "
            "Fill in the eps_prime and sigma_S_per_m columns with values "
            "looked up on the official calculator before running."
        )

    idx = np.argsort(freqs)
    return np.array(freqs)[idx], np.array(eps_vals)[idx], np.array(sigma_vals)[idx]


# ===========================================================================
# Plots
# ===========================================================================

def plot_full_spectrum_with_band(f_full, Z_full, f_band, Z_band, band_range, save_path=None):
    """Show the full spectrum (Gabriel model) with the beta sub-band highlighted -- an honest view of 'everything' vs. 'identifiable'."""
    fig, (ax_ny, ax_mod, ax_ph) = plt.subplots(1, 3, figsize=(14, 4))

    ax_ny.plot(Z_full.real, -Z_full.imag, '--', color="gray", alpha=0.6,
               label="Full spectrum (Gabriel 4-CC)")
    ax_ny.plot(Z_band.real, -Z_band.imag, 'o-', color="#1f77b4", ms=4,
               label=f"Beta sub-band [{band_range[0]:.0f}, {band_range[1]:.0f}] Hz")
    ax_ny.set_xlabel(r"$\Re[Z]$ [Ohm]"); ax_ny.set_ylabel(r"$-\Im[Z]$ [Ohm]")
    ax_ny.set_title("(a) Nyquist"); ax_ny.legend(fontsize=8)

    ax_mod.loglog(f_full, np.abs(Z_full), '--', color="gray", alpha=0.6, label="Full")
    ax_mod.loglog(f_band, np.abs(Z_band), 'o-', color="#1f77b4", ms=4, label="Beta sub-band")
    ax_mod.axvspan(*band_range, alpha=0.1, color="#1f77b4")
    ax_mod.set_xlabel("Frequency [Hz]"); ax_mod.set_ylabel(r"$|Z|$ [Ohm]")
    ax_mod.set_title("(b) Magnitude"); ax_mod.legend(fontsize=8)

    ax_ph.semilogx(f_full, np.angle(Z_full, deg=True), '--', color="gray", alpha=0.6)
    ax_ph.semilogx(f_band, np.angle(Z_band, deg=True), 'o-', color="#1f77b4", ms=4)
    ax_ph.axvspan(*band_range, alpha=0.1, color="#1f77b4")
    ax_ph.set_xlabel("Frequency [Hz]"); ax_ph.set_ylabel("Phase [deg]")
    ax_ph.set_title("(c) Phase")

    fig.suptitle("Full Dielectric Spectrum (Gabriel 4-CC) vs. Identifiable Sub-band",
                 fontsize=12, fontweight="bold")
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, bbox_inches="tight", dpi=150)
        print(f"  Figure saved: {save_path}")
    plt.show()
    return fig


def plot_subband_fit_result(result, save_path=None):
    """Show the single-dispersion Cole-Cole fit within the beta sub-band."""
    from src.analysis import samples_to_physical

    f_band, z_band = result["f_band"], result["Z_band"]
    phys = samples_to_physical(result["mcmc_samples"])
    r_med, r0_med = np.median(phys["R_inf"]), np.median(phys["R0"])
    tau_med, alpha_med = np.median(phys["tau"]), np.median(phys["alpha"])
    z_fit = cole_cole_impedance(f_band, r_med, r0_med, tau_med, alpha_med)

    fig, (ax_ny, ax_mod, ax_ph) = plt.subplots(1, 3, figsize=(14, 4))

    ax_ny.scatter(z_band.real, -z_band.imag, color="gray", s=25,
                  label="Data (beta sub-band)", zorder=5)
    ax_ny.plot(z_fit.real, -z_fit.imag, color="#1f77b4", lw=2,
               label="Cole-Cole fit (1 dispersion)")
    ax_ny.set_xlabel(r"$\Re[Z]$ [Ohm]"); ax_ny.set_ylabel(r"$-\Im[Z]$ [Ohm]")
    ax_ny.set_title(f"(a) Nyquist -- R2={result['r_squared_subband']:.4f}")
    ax_ny.legend(fontsize=8); ax_ny.set_aspect("equal", adjustable="datalim")

    ax_mod.semilogx(f_band, np.abs(z_band), 'o', color="gray", ms=5)
    ax_mod.semilogx(f_band, np.abs(z_fit), color="#1f77b4", lw=2)
    ax_mod.set_xlabel("Frequency [Hz]"); ax_mod.set_ylabel(r"$|Z|$ [Ohm]")
    ax_mod.set_title("(b) Magnitude")

    ax_ph.semilogx(f_band, np.angle(z_band, deg=True), 'o', color="gray", ms=5)
    ax_ph.semilogx(f_band, np.angle(z_fit, deg=True), color="#1f77b4", lw=2)
    ax_ph.set_xlabel("Frequency [Hz]"); ax_ph.set_ylabel("Phase [deg]")
    ax_ph.set_title("(c) Phase")

    cov_pct = result["coverage_fraction"] * 100
    fig.suptitle(f"Cole-Cole Fit -- Honest Beta Sub-band ({cov_pct:.0f}% of the full spectrum)",
                 fontsize=12, fontweight="bold")
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, bbox_inches="tight", dpi=150)
        print(f"  Figure saved: {save_path}")
    plt.show()
    return fig


# ===========================================================================
# Pipelines
# ===========================================================================

def run_demo_mode(n_samples, n_warmup, seed, output_dir):
    """Demo mode: uses MUSCLE_4CC_PARTIAL (UNVERIFIED parameters) only to check that the code runs. Do NOT use for the paper."""
    print("\n" + "WARNING " * 8)
    print("  DEMO MODE -- UNVERIFIED parameters")
    print("  Do NOT use these results in the final paper.")
    print("  Run with --csv-fcc or --csv-itis after consulting an official source.")
    print("WARNING " * 8 + "\n")

    os.makedirs(output_dir, exist_ok=True)
    f_full = frequency_grid(10.0, 1e8, 200)   # wide band to see all 4 dispersions
    z_full = impedance_from_4cc(f_full, MUSCLE_4CC_PARTIAL)

    f_grid = frequency_grid(100.0, 1e6, 30)   # our experimental grid
    z_grid = impedance_from_4cc(f_grid, MUSCLE_4CC_PARTIAL)

    f_band, z_band_clean = select_beta_band(f_grid, z_grid, 1e3, 1e6)
    plot_full_spectrum_with_band(f_full, z_full, f_band, z_band_clean, (1e3, 1e6),
                                  save_path=os.path.join(output_dir, "demo_full_spectrum_vs_band.png"))

    result = fit_single_cole_cole_subband(f_grid, z_grid, f_low=1e3, f_high=1e6,
                                           snr_db=30.0, n_samples=n_samples,
                                           n_warmup=n_warmup, seed=seed)

    print(f"\n  R2 (sub-band): {result['r_squared_subband']:.4f}")
    print(f"  Coverage: {result['coverage_fraction']*100:.0f}% of the full spectrum")
    p = result["params_median"]
    print(f"  R_inf={p['R_inf']:.2f} Ohm  R0={p['R0']:.2f} Ohm  "
          f"tau={p['tau']*1e6:.2f} us  alpha={p['alpha']:.3f}")

    plot_subband_fit_result(result, save_path=os.path.join(output_dir, "demo_subband_fit.png"))
    return result


def run_itis_csv_mode(csv_path, n_samples, n_warmup, seed, output_dir,
                       snr_db=30.0, r_inf_calib=50.0):
    """Pipeline using raw Gabriel (4-CC) parameters read from the official IT'IS Foundation spreadsheet -- the RECOMMENDED validation route (one file, all tissues, no point-by-point lookups)."""
    print("\n" + "=" * 60)
    print("  OPTION C (v2) -- Validation with the IT'IS Foundation database")
    print("  Primary source: Gabriel et al. (1996)")
    print("=" * 60)

    os.makedirs(output_dir, exist_ok=True)
    tissues = load_itis_csv(csv_path)

    results = {}
    for name, params in tissues.items():
        print(f"\n  -- Tissue: {name} --")

        if not validate_physical_parameters(params):
            print(f"  Skipping '{name}' -- fix the parameters and re-run.")
            continue

        f_grid = frequency_grid(100.0, 1e6, 30)
        z_grid = impedance_from_4cc_calibrated(f_grid, params, target_r_inf=r_inf_calib, f_ref=1e6)
        f_band, z_band_clean = select_beta_band(f_grid, z_grid, 1e3, 1e6)
        print(f"  Beta sub-band: {len(f_band)}/{len(f_grid)} points "
              f"({len(f_band)/len(f_grid)*100:.0f}%)")

        plot_full_spectrum_with_band(f_grid, z_grid, f_band, z_band_clean, (1e3, 1e6),
                                      save_path=os.path.join(output_dir, f"{name}_full_spectrum_vs_band.png"))

        result = fit_single_cole_cole_subband(f_grid, z_grid, f_low=1e3, f_high=1e6,
                                               snr_db=snr_db, n_samples=n_samples,
                                               n_warmup=n_warmup, seed=seed)

        print(f"  R2 (sub-band): {result['r_squared_subband']:.4f}")
        p = result["params_median"]
        print(f"  R_inf={p['R_inf']:.2f} Ohm  R0={p['R0']:.2f} Ohm  "
              f"tau={p['tau']*1e6:.2f} us  alpha={p['alpha']:.3f}")

        plot_subband_fit_result(result, save_path=os.path.join(output_dir, f"{name}_subband_fit.png"))
        results[name] = result

    print(f"\n  Results saved to: {os.path.abspath(output_dir)}/")
    return results


def run_fcc_csv_mode(csv_path, n_samples, n_warmup, seed, output_dir, snr_db=30.0):
    """Pipeline using real data looked up on the official FCC/IFAC-CNR calculator -- the scientifically honest validation route for the paper."""
    print("\n" + "=" * 60)
    print("  OPTION C -- Validation with official FCC/IFAC-CNR data")
    print("=" * 60)

    os.makedirs(output_dir, exist_ok=True)
    f_fcc, eps_fcc, sigma_fcc = load_fcc_csv(csv_path)
    print(f"\n  Loaded {len(f_fcc)} points from '{csv_path}'")
    print(f"  Range: [{f_fcc.min():.0f}, {f_fcc.max():.0f}] Hz")

    z_full = impedance_from_eps_sigma(f_fcc, eps_fcc, sigma_fcc)
    print(f"  |Z| range: [{np.abs(z_full).min():.2f}, {np.abs(z_full).max():.2f}] Ohm")

    f_band, z_band_clean = select_beta_band(f_fcc, z_full, 1e3, 1e6)
    print(f"  Beta sub-band: {len(f_band)}/{len(f_fcc)} points")

    plot_full_spectrum_with_band(f_fcc, z_full, f_band, z_band_clean, (1e3, 1e6),
                                  save_path=os.path.join(output_dir, "fcc_full_spectrum_vs_band.png"))

    result = fit_single_cole_cole_subband(f_fcc, z_full, f_low=1e3, f_high=1e6,
                                           snr_db=snr_db, n_samples=n_samples,
                                           n_warmup=n_warmup, seed=seed)

    print(f"\n  R2 (sub-band): {result['r_squared_subband']:.4f}")
    print(f"  Coverage: {result['coverage_fraction']*100:.0f}% of the full spectrum")
    p = result["params_median"]
    print(f"  R_inf={p['R_inf']:.2f} Ohm  R0={p['R0']:.2f} Ohm  "
          f"tau={p['tau']*1e6:.2f} us  alpha={p['alpha']:.3f}")

    plot_subband_fit_result(result, save_path=os.path.join(output_dir, "fcc_subband_fit.png"))
    print(f"\n  Results saved to: {os.path.abspath(output_dir)}/")
    return result


# ===========================================================================
# CLI
# ===========================================================================

def parse_args():
    p = argparse.ArgumentParser(description="Option C -- Honest band-limited validation")
    p.add_argument("--generate-template", dest="generate_template", action="store_true",
                   help="[Legacy] Generate a CSV template for a manual FCC lookup")
    p.add_argument("--generate-template-itis", dest="generate_template_itis", action="store_true",
                   help="[RECOMMENDED] Generate a CSV template to fill in from the "
                        "official IT'IS Foundation spreadsheet (14 params/tissue)")
    p.add_argument("--csv-fcc", type=str, default=None,
                   help="[Legacy] CSV with (freq, eps', sigma) looked up on the FCC site")
    p.add_argument("--csv-itis", type=str, default=None,
                   help="[RECOMMENDED] CSV with the 14 4-CC parameters read from the "
                        "official IT'IS Foundation spreadsheet")
    p.add_argument("--r-inf-calib", type=float, default=50.0,
                   help="Reference resistance [Ohm] to calibrate the unknown measurement "
                        "geometry (default: 50 Ohm, typical for soft tissue)")
    p.add_argument("--demo", action="store_true",
                   help="Demo mode (UNVERIFIED parameters, code testing only)")
    p.add_argument("--fast", action="store_true")
    p.add_argument("--snr", type=float, default=30.0)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--output", type=str, default="results_option_c")
    return p.parse_args()


def main():
    args = parse_args()

    if args.generate_template:
        generate_fcc_csv_template()
        return
    if args.generate_template_itis:
        generate_itis_csv_template()
        return

    n_samples = 1500 if args.fast else 4000
    n_warmup = 750 if args.fast else 2000

    if args.csv_itis:
        run_itis_csv_mode(args.csv_itis, n_samples, n_warmup, args.seed,
                           args.output, args.snr, args.r_inf_calib)
    elif args.csv_fcc:
        run_fcc_csv_mode(args.csv_fcc, n_samples, n_warmup, args.seed,
                          args.output, args.snr)
    elif args.demo:
        run_demo_mode(n_samples, n_warmup, args.seed, args.output)
    else:
        print("Please specify an option:")
        print("  --generate-template-itis  (RECOMMENDED -- one-time download)")
        print("  --csv-itis <file>         (RECOMMENDED -- run with real data)")
        print("  --generate-template / --csv-fcc <file>  (legacy, manual)")
        print("  --demo                    (code testing only)")
        print("Use --help for more information")


if __name__ == "__main__":
    main()
